### ISSUE TITLE
Error: Cannot find plist

### ISSUE THREAD

**Issue by Azair79** [nowsecure/node-applesign#152]
Hi i am trying to resign an file with my provisioning profile but i keep getting the following error

```
Error: Cannot find plist
    at findIdentityFromProvisionSync (/opt/homebrew/lib/node_modules/applesign/lib/idprov.js:11:11)
    at Object.fromOptions (/opt/homebrew/lib/node_modules/applesign/lib/config.js:137:19)
    at new Applesign (/opt/homebrew/lib/node_modules/applesign/index.js:28:26)
    at main (/opt/homebrew/lib/node_modules/applesign/bin/applesign.js:20:14)
    at Object.<anonymous> (/opt/homebrew/lib/node_modules/applesign/bin/applesign.js:70:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
```

my syntax for running applesign is

bin/applesign.js -i 13A6BDE0419813AXXXXXXXXXXX -b funky-dude -m ~/test/ready.zip -o ~/test/ready.ipa

any clues as to what may be going wrong here?

**Comment by ditorri1** [comment]
I will be interested in the solution as well, thank you

**Comment by trufae** [comment]
This error is probably not very clear, but by reading the line and the code this happens when you provide an invalid file as argument to `-m `. this option expects a `.mobileprovision` file, but in your case you are passing a .zip file so it's unable to identify the signing key from there.

For user compiled apps the key is derived from the identifier by picking it from the keychain, so as a first try i would say to remove the `-m ~/test/ready.zip` from your line and check if it works.
