### ISSUE TITLE
Error: Cannot find module './depsolver'

### ISSUE THREAD

**Issue by dweinstein** [nowsecure/node-applesign#37]
```
module.js:341
    throw err;
    ^

Error: Cannot find module './depsolver'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/user/.nvm/versions/node/v5.10.0/lib/node_modules/applesign/session.js:11:19)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

**Comment by dweinstein** [comment]
fixed in #38
