### ISSUE TITLE
Cannot find module 'macho'

### ISSUE THREAD

**Issue by ay-kay** [nowsecure/node-applesign#57]
Cloned latest master and installed using `npm install`.

```
$ bin/ipa-resign.js
module.js:472
    throw err;
    ^

Error: Cannot find module 'macho'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (node-applesign/depsolver.js:4:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by ay-kay** [comment]
depsolver.js

-const macho = require('macho');
+const macho = require('@nowsecure/macho');

**Comment by semml0r** [comment]
thanks @ay-kay. I can confirm his solution, works for me.

**Comment by joanbono** [comment]
Works here too using `npm 3.10.10`.

Thanks @ay-kay

**Comment by trufae** [comment]
should be working now
