### ISSUE TITLE
TypeError: Cannot read property 'cmds' of undefined

### ISSUE THREAD

**Issue by dweinstein** [nowsecure/node-applesign#61]
```
/Users/user/.nvm/versions/node/v7.5.0/lib/node_modules/applesign/depsolver.js:85
      const libs = exec.cmds.filter((x) => {
TypeError: Cannot read property 'cmds' of undefined
    at fs.readFile (/Users/user/.nvm/versions/node/v7.5.0/lib/node_modules/applesign/depsolver.js:85:24)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:416:3)
```

using https://github.com/nowsecure/node-applesign/commit/ab8f4ea390123634b0697225bbd911ad0f7cc046

cc @jporter22

**Comment by dweinstein** [comment]
this seems to happen on a framework that is missing the `LC_CODE_SIGNATURE` cmd.
