### ISSUE TITLE
Applesign v2.2.0 - maxBuffer exceeded / large iPA?

### ISSUE THREAD

**Issue by rustymagnet3000** [nowsecure/node-applesign#71]
I always hit the following error on a large IPA.  I don't get the error on a small IPA.

Any ideas what is causing this error with command?
`applesign -i <SIGNING ID> repackaged.ipa`

```
{ Error: stdout maxBuffer exceeded
    at Socket.onChildStdout (child_process.js:328:14)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
  cmd: '/usr/bin/unzip -o /PATH_TO_DIRECTORY/repackaged.ipa -d /PATH_TO_DIRECTORY/repackaged.ipa.5fdc0187-7280-4fb9-8e99-c3843fd81b29' } undefined
```

**Comment by rustymagnet3000** [comment]
`applesign --version` ✅
`applesign -L`✅

**Comment by rustymagnet3000** [comment]
if I try the -z flag to ignore zip errors, I get more errors that suggest the Info.plist is not present in the inside the app package, but I know it is.

**Comment by rustymagnet3000** [comment]
ok, this looks like a sudo or chown  issue.  When I run Applesign with su, it works.

**Comment by rustymagnet3000** [comment]
The issue seems to be related to the IPA size.

**Comment by rustymagnet3000** [comment]
Interestingly, when I run Objection [that uses Applesign] it works. ✅

But I still hit the same error..

> Unzipping /path_to_ipa/myapp.ipa
> Cleaning up /path_to_ipa/myapp.ipa.c1733058-546c-41e2-8d13-1e32763f3b32
> Cleaning up /path_to_ipa/myapp.ipa.c1733058-546c-41e2-8d13-1e32763f3b32
> Cleaning up /path_to_ipa/myapp.ipa.c1733058-546c-41e2-8d13-1e32763f3b32
> { Error: stdout maxBuffer exceeded

**Comment by rustymagnet3000** [comment]
Fix: used the 7zip flag instead of zip.

`applesign -7 -i DEVELOPER_ID -m embedded.mobileprovision myapp.ipa`

I suspect this was a self-inflicted 'chown' issue.
