### ISSUE TITLE
Wildcard profiles return error

### ISSUE THREAD

**Issue by platix** [nowsecure/node-applesign#84]
A wildcard profile (APP ID: STRING.*) returns this error:

Error: Cannot find an identity for this mobile provisioning file.
    at findIdentityFromProvisionSync (/usr/local/lib/node_modules/applesign/lib/idprov.js:25:9)
    at Object.fromOptions (/usr/local/lib/node_modules/applesign/lib/config.js:72:19)
    at new Applesign (/usr/local/lib/node_modules/applesign/index.js:25:26)
    at main (/usr/local/lib/node_modules/applesign/bin/applesign.js:19:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/applesign/bin/applesign.js:62:1)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)

**Comment by trufae** [comment]
Can you test if this branch works for you? https://github.com/nowsecure/node-applesign/pull/103
